import { Role } from './types';

export const API_PREFIX = '/api/v1';

export const ROLES = {
  FRONTLINE_WORKER: Role.FRONTLINE_WORKER,
  SENDING_FACILITY: Role.SENDING_FACILITY,
  RECEIVING_FACILITY: Role.RECEIVING_FACILITY,
  CLINICIAN: Role.CLINICIAN,
  DISTRICT_SUPERVISOR: Role.DISTRICT_SUPERVISOR,
  ADMINISTRATOR: Role.ADMINISTRATOR,
  CLINICAL_ADMINISTRATOR: Role.CLINICAL_ADMINISTRATOR,
} as const;

export const ADMIN_ROLES: Role[] = [Role.ADMINISTRATOR];
export const CLINICAL_ADMIN_ROLES: Role[] = [Role.CLINICAL_ADMINISTRATOR, Role.ADMINISTRATOR];
export const SUPERVISOR_ROLES: Role[] = [Role.DISTRICT_SUPERVISOR, Role.ADMINISTRATOR];
export const CLINICIAN_ROLES: Role[] = [Role.CLINICIAN, Role.RECEIVING_FACILITY];
export const FACILITY_ROLES: Role[] = [Role.SENDING_FACILITY, Role.RECEIVING_FACILITY, Role.CLINICIAN];

export const BLACKSPOT_CONFIG = {
  get MIN_CASE_COUNT_THRESHOLD(): number {
    return parseInt(process.env.MIN_CASE_COUNT_BLACKSPOT_THRESHOLD || '5', 10);
  },
  PILOT_DISCLAIMER: 'Pilot-period, synthetic-data only. Aggregated output suppressed below minimum case threshold.',
};

export const GAPSENSE_CONFIG = {
  DEFAULT_ACKNOWLEDGEMENT_TIMEOUT_MINUTES: 30,
  DEFAULT_DISPOSITION_TIMEOUT_HOURS: 4,
  DEFAULT_FOLLOW_UP_WINDOW_DAYS: 3,
  LABEL: 'likely cause, pending supervisor review',
};
